# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddf18a63ff84dfc1d85f6ee4d7a2dd45cc74f5dc9ef2496e255c7570068397a299a2e46aaed8f065e2d2d0188fa677fe020af82d33cd2e5a5b80890087a8521c

test:
  secret_key_base: 16d714c7a4eab947542fa572bc4945e4a06b573f51907b8ecd5db9495733679aee2196b0165a648b876dd4d2be7f7de97064409840a6df319b4439a8a11b56f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
